/*
 * generated by Xtext 2.9.2
 */
package edu.kit.ipd.sdq.cbsmdsl.parser.antlr;

import com.google.inject.Inject;
import edu.kit.ipd.sdq.cbsmdsl.parser.antlr.internal.InternalCBSMDslParser;
import edu.kit.ipd.sdq.cbsmdsl.services.CBSMDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CBSMDslParser extends AbstractAntlrParser {

	@Inject
	private CBSMDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCBSMDslParser createParser(XtextTokenStream stream) {
		return new InternalCBSMDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "CompleteArchitecture";
	}

	public CBSMDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CBSMDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
