/*
 * generated by Xtext 2.9.2
 */
package edu.kit.ipd.sdq.cbsmdsl.parser.antlr;

import com.google.inject.Inject;
import edu.kit.ipd.sdq.cbsmdsl.parser.antlr.internal.InternalCbsmDslParser;
import edu.kit.ipd.sdq.cbsmdsl.services.CbsmDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CbsmDslParser extends AbstractAntlrParser {

	@Inject
	private CbsmDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCbsmDslParser createParser(XtextTokenStream stream) {
		return new InternalCbsmDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ViewType";
	}

	public CbsmDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CbsmDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
