/*
<<<<<<< HEAD
 * generated by Xtext 2.9.1
=======
 * generated by Xtext
>>>>>>> 624daea66344a9d43745cf9a36e8187215bc46ca
 */
package edu.kit.ipd.sdq.cbsmdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CbsmDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("edu/kit/ipd/sdq/cbsmdsl/parser/antlr/internal/InternalCbsmDsl.tokens");
	}
}
