/**
 *
 * $Id$
 */
package edu.kit.ipd.sdq.cbsm.environment.validation;

import edu.kit.ipd.sdq.cbsm.environment.Container;
import edu.kit.ipd.sdq.cbsm.environment.Environment;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link edu.kit.ipd.sdq.cbsm.environment.Link}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LinkValidator {
	boolean validate();

	boolean validateParentEnvironment(Environment value);
	boolean validateLinkedContainers(EList<Container> value);
}
