/**
 *
 * $Id$
 */
package edu.kit.ipd.sdq.cbsm.allocation.validation;

import edu.kit.ipd.sdq.cbsm.assembly.AssemblyContext;

import edu.kit.ipd.sdq.cbsm.environment.Container;

/**
 * A sample validator interface for {@link edu.kit.ipd.sdq.cbsm.allocation.AllocationContext}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AllocationContextValidator {
	boolean validate();

	boolean validateAllocatedContainer(Container value);
	boolean validateAllocatedAssemblyContext(AssemblyContext value);
}
