/**
 *
 * $Id$
 */
package edu.kit.ipd.sdq.cbsm.assembly.validation;

import edu.kit.ipd.sdq.cbsm.repository.RequiredRole;

/**
 * A sample validator interface for {@link edu.kit.ipd.sdq.cbsm.assembly.RequiredDelegationConnector}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RequiredDelegationConnectorValidator {
	boolean validate();

	boolean validateInnerRequiredRole(RequiredRole value);
	boolean validateOuterRequiredRole(RequiredRole value);
}
