/**
 * generated by Xtext 2.9.2
 */
package edu.kit.ipd.sdq.cbsmdsl.scoping;

import edu.kit.ipd.sdq.cbsmdsl.scoping.AbstractCbsmDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class CbsmDslScopeProvider extends AbstractCbsmDslScopeProvider {
}
