/**
 * generated by Xtext 2.9.2
 */
package edu.kit.ipd.sdq.cbsmdsl.validation;

import edu.kit.ipd.sdq.cbsmdsl.validation.AbstractCbsmDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CbsmDslValidator extends AbstractCbsmDslValidator {
}
