/**
 * generated by Xtext 2.9.2
 */
package edu.kit.ipd.sdq.cbsmdsl;

import edu.kit.ipd.sdq.cbsmdsl.CBSMDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CBSMDslStandaloneSetup extends CBSMDslStandaloneSetupGenerated {
  public static void doSetup() {
    CBSMDslStandaloneSetup _cBSMDslStandaloneSetup = new CBSMDslStandaloneSetup();
    _cBSMDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
