/**
 * generated by Xtext 2.9.2
 */
package edu.kit.ipd.sdq.cbsmdsl;

import edu.kit.ipd.sdq.cbsmdsl.AbstractCbsmDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CbsmDslRuntimeModule extends AbstractCbsmDslRuntimeModule {
}
