/*
 * generated by Xtext
 */
package edu.kit.ipd.sdq.cbsmdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCbsmDslScopeProvider extends DelegatingScopeProvider {
}
