/*
<<<<<<< HEAD
 * generated by Xtext 2.9.1
=======
 * generated by Xtext
>>>>>>> 624daea66344a9d43745cf9a36e8187215bc46ca
 */
package edu.kit.ipd.sdq.cbsmdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCbsmDslScopeProvider extends DelegatingScopeProvider {
}
