/**
 *
 * $Id$
 */
package edu.kit.ipd.sdq.cbsm.repository.validation;

import edu.kit.ipd.sdq.cbsm.repository.DataType;
import edu.kit.ipd.sdq.cbsm.repository.Parameter;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link edu.kit.ipd.sdq.cbsm.repository.Signature}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SignatureValidator {
	boolean validate();

	boolean validateReturnType(DataType value);
	boolean validateParameters(EList<Parameter> value);
}
