/*
 * generated by Xtext 2.9.2
 */
package edu.kit.ipd.sdq.cbsmdsl.ide.contentassist.antlr;

import com.google.inject.Inject;
import edu.kit.ipd.sdq.cbsmdsl.ide.contentassist.antlr.internal.InternalCbsmDslParser;
import edu.kit.ipd.sdq.cbsmdsl.services.CbsmDslGrammarAccess;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class CbsmDslParser extends AbstractContentAssistParser {

	@Inject
	private CbsmDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalCbsmDslParser createParser() {
		InternalCbsmDslParser result = new InternalCbsmDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getViewTypeAccess().getAlternatives(), "rule__ViewType__Alternatives");
					put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
					put(grammarAccess.getConnectorAccess().getAlternatives(), "rule__Connector__Alternatives");
					put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getSimpleTypeInstanceAccess().getAlternatives(), "rule__SimpleTypeInstance__Alternatives");
					put(grammarAccess.getRepositoryAccess().getGroup(), "rule__Repository__Group__0");
					put(grammarAccess.getRepositoryAccess().getGroup_3(), "rule__Repository__Group_3__0");
					put(grammarAccess.getRepositoryAccess().getGroup_3_3(), "rule__Repository__Group_3_3__0");
					put(grammarAccess.getRepositoryAccess().getGroup_4(), "rule__Repository__Group_4__0");
					put(grammarAccess.getRepositoryAccess().getGroup_4_3(), "rule__Repository__Group_4_3__0");
					put(grammarAccess.getRepositoryAccess().getGroup_5(), "rule__Repository__Group_5__0");
					put(grammarAccess.getRepositoryAccess().getGroup_5_3(), "rule__Repository__Group_5_3__0");
					put(grammarAccess.getSystemAccess().getGroup(), "rule__System__Group__0");
					put(grammarAccess.getSystemAccess().getGroup_3(), "rule__System__Group_3__0");
					put(grammarAccess.getSystemAccess().getGroup_3_3(), "rule__System__Group_3_3__0");
					put(grammarAccess.getSystemAccess().getGroup_4(), "rule__System__Group_4__0");
					put(grammarAccess.getSystemAccess().getGroup_4_3(), "rule__System__Group_4_3__0");
					put(grammarAccess.getSystemAccess().getGroup_5(), "rule__System__Group_5__0");
					put(grammarAccess.getSystemAccess().getGroup_5_3(), "rule__System__Group_5_3__0");
					put(grammarAccess.getSystemAccess().getGroup_6(), "rule__System__Group_6__0");
					put(grammarAccess.getSystemAccess().getGroup_6_3(), "rule__System__Group_6_3__0");
					put(grammarAccess.getEnvironmentAccess().getGroup(), "rule__Environment__Group__0");
					put(grammarAccess.getEnvironmentAccess().getGroup_3(), "rule__Environment__Group_3__0");
					put(grammarAccess.getEnvironmentAccess().getGroup_3_3(), "rule__Environment__Group_3_3__0");
					put(grammarAccess.getEnvironmentAccess().getGroup_4(), "rule__Environment__Group_4__0");
					put(grammarAccess.getEnvironmentAccess().getGroup_4_3(), "rule__Environment__Group_4_3__0");
					put(grammarAccess.getAllocationAccess().getGroup(), "rule__Allocation__Group__0");
					put(grammarAccess.getAllocationAccess().getGroup_3(), "rule__Allocation__Group_3__0");
					put(grammarAccess.getAllocationAccess().getGroup_3_3(), "rule__Allocation__Group_3_3__0");
					put(grammarAccess.getInterfaceAccess().getGroup(), "rule__Interface__Group__0");
					put(grammarAccess.getInterfaceAccess().getGroup_4(), "rule__Interface__Group_4__0");
					put(grammarAccess.getInterfaceAccess().getGroup_4_3(), "rule__Interface__Group_4_3__0");
					put(grammarAccess.getComponentAccess().getGroup(), "rule__Component__Group__0");
					put(grammarAccess.getComponentAccess().getGroup_4(), "rule__Component__Group_4__0");
					put(grammarAccess.getComponentAccess().getGroup_4_3(), "rule__Component__Group_4_3__0");
					put(grammarAccess.getComponentAccess().getGroup_5(), "rule__Component__Group_5__0");
					put(grammarAccess.getComponentAccess().getGroup_5_3(), "rule__Component__Group_5_3__0");
					put(grammarAccess.getComponentAccess().getGroup_6(), "rule__Component__Group_6__0");
					put(grammarAccess.getSignatureAccess().getGroup(), "rule__Signature__Group__0");
					put(grammarAccess.getSignatureAccess().getGroup_4(), "rule__Signature__Group_4__0");
					put(grammarAccess.getSignatureAccess().getGroup_5(), "rule__Signature__Group_5__0");
					put(grammarAccess.getSignatureAccess().getGroup_5_3(), "rule__Signature__Group_5_3__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getProvidedRoleAccess().getGroup(), "rule__ProvidedRole__Group__0");
					put(grammarAccess.getRequiredRoleAccess().getGroup(), "rule__RequiredRole__Group__0");
					put(grammarAccess.getBehaviorDescriptionAccess().getGroup(), "rule__BehaviorDescription__Group__0");
					put(grammarAccess.getBehaviorDescriptionAccess().getGroup_3(), "rule__BehaviorDescription__Group_3__0");
					put(grammarAccess.getBehaviorDescriptionAccess().getGroup_3_3(), "rule__BehaviorDescription__Group_3_3__0");
					put(grammarAccess.getAction_ImplAccess().getGroup(), "rule__Action_Impl__Group__0");
					put(grammarAccess.getAction_ImplAccess().getGroup_4(), "rule__Action_Impl__Group_4__0");
					put(grammarAccess.getAction_ImplAccess().getGroup_5(), "rule__Action_Impl__Group_5__0");
					put(grammarAccess.getInternalActionAccess().getGroup(), "rule__InternalAction__Group__0");
					put(grammarAccess.getInternalActionAccess().getGroup_4(), "rule__InternalAction__Group_4__0");
					put(grammarAccess.getInternalActionAccess().getGroup_5(), "rule__InternalAction__Group_5__0");
					put(grammarAccess.getExternalCallAccess().getGroup(), "rule__ExternalCall__Group__0");
					put(grammarAccess.getExternalCallAccess().getGroup_3(), "rule__ExternalCall__Group_3__0");
					put(grammarAccess.getExternalCallAccess().getGroup_4(), "rule__ExternalCall__Group_4__0");
					put(grammarAccess.getLoopAccess().getGroup(), "rule__Loop__Group__0");
					put(grammarAccess.getLoopAccess().getGroup_4(), "rule__Loop__Group_4__0");
					put(grammarAccess.getLoopAccess().getGroup_5(), "rule__Loop__Group_5__0");
					put(grammarAccess.getLoopAccess().getGroup_6(), "rule__Loop__Group_6__0");
					put(grammarAccess.getLoopAccess().getGroup_6_3(), "rule__Loop__Group_6_3__0");
					put(grammarAccess.getBranchAccess().getGroup(), "rule__Branch__Group__0");
					put(grammarAccess.getBranchAccess().getGroup_4(), "rule__Branch__Group_4__0");
					put(grammarAccess.getBranchAccess().getGroup_5(), "rule__Branch__Group_5__0");
					put(grammarAccess.getBranchAccess().getGroup_6(), "rule__Branch__Group_6__0");
					put(grammarAccess.getBranchAccess().getGroup_6_3(), "rule__Branch__Group_6_3__0");
					put(grammarAccess.getBranchPathAccess().getGroup(), "rule__BranchPath__Group__0");
					put(grammarAccess.getBranchPathAccess().getGroup_4(), "rule__BranchPath__Group_4__0");
					put(grammarAccess.getBranchPathAccess().getGroup_4_3(), "rule__BranchPath__Group_4_3__0");
					put(grammarAccess.getComplexTypeAccess().getGroup(), "rule__ComplexType__Group__0");
					put(grammarAccess.getSimpleTypeAccess().getGroup(), "rule__SimpleType__Group__0");
					put(grammarAccess.getAssemblyContextAccess().getGroup(), "rule__AssemblyContext__Group__0");
					put(grammarAccess.getProvidedDelegationConnectorAccess().getGroup(), "rule__ProvidedDelegationConnector__Group__0");
					put(grammarAccess.getRequiredDelegationConnectorAccess().getGroup(), "rule__RequiredDelegationConnector__Group__0");
					put(grammarAccess.getAssemblyConnectorAccess().getGroup(), "rule__AssemblyConnector__Group__0");
					put(grammarAccess.getContainerAccess().getGroup(), "rule__Container__Group__0");
					put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
					put(grammarAccess.getLinkAccess().getGroup_6(), "rule__Link__Group_6__0");
					put(grammarAccess.getAllocationContextAccess().getGroup(), "rule__AllocationContext__Group__0");
					put(grammarAccess.getRepositoryAccess().getInterfacesAssignment_3_2(), "rule__Repository__InterfacesAssignment_3_2");
					put(grammarAccess.getRepositoryAccess().getInterfacesAssignment_3_3_1(), "rule__Repository__InterfacesAssignment_3_3_1");
					put(grammarAccess.getRepositoryAccess().getComponentsAssignment_4_2(), "rule__Repository__ComponentsAssignment_4_2");
					put(grammarAccess.getRepositoryAccess().getComponentsAssignment_4_3_1(), "rule__Repository__ComponentsAssignment_4_3_1");
					put(grammarAccess.getRepositoryAccess().getDataTypesAssignment_5_2(), "rule__Repository__DataTypesAssignment_5_2");
					put(grammarAccess.getRepositoryAccess().getDataTypesAssignment_5_3_1(), "rule__Repository__DataTypesAssignment_5_3_1");
					put(grammarAccess.getSystemAccess().getProvidedRolesAssignment_3_2(), "rule__System__ProvidedRolesAssignment_3_2");
					put(grammarAccess.getSystemAccess().getProvidedRolesAssignment_3_3_1(), "rule__System__ProvidedRolesAssignment_3_3_1");
					put(grammarAccess.getSystemAccess().getRequiredRolesAssignment_4_2(), "rule__System__RequiredRolesAssignment_4_2");
					put(grammarAccess.getSystemAccess().getRequiredRolesAssignment_4_3_1(), "rule__System__RequiredRolesAssignment_4_3_1");
					put(grammarAccess.getSystemAccess().getContainedAssemblyContextsAssignment_5_2(), "rule__System__ContainedAssemblyContextsAssignment_5_2");
					put(grammarAccess.getSystemAccess().getContainedAssemblyContextsAssignment_5_3_1(), "rule__System__ContainedAssemblyContextsAssignment_5_3_1");
					put(grammarAccess.getSystemAccess().getSystemConnectorsAssignment_6_2(), "rule__System__SystemConnectorsAssignment_6_2");
					put(grammarAccess.getSystemAccess().getSystemConnectorsAssignment_6_3_1(), "rule__System__SystemConnectorsAssignment_6_3_1");
					put(grammarAccess.getEnvironmentAccess().getContainersAssignment_3_2(), "rule__Environment__ContainersAssignment_3_2");
					put(grammarAccess.getEnvironmentAccess().getContainersAssignment_3_3_1(), "rule__Environment__ContainersAssignment_3_3_1");
					put(grammarAccess.getEnvironmentAccess().getLinksAssignment_4_2(), "rule__Environment__LinksAssignment_4_2");
					put(grammarAccess.getEnvironmentAccess().getLinksAssignment_4_3_1(), "rule__Environment__LinksAssignment_4_3_1");
					put(grammarAccess.getAllocationAccess().getAllocationContextsAssignment_3_2(), "rule__Allocation__AllocationContextsAssignment_3_2");
					put(grammarAccess.getAllocationAccess().getAllocationContextsAssignment_3_3_1(), "rule__Allocation__AllocationContextsAssignment_3_3_1");
					put(grammarAccess.getInterfaceAccess().getNameAssignment_2(), "rule__Interface__NameAssignment_2");
					put(grammarAccess.getInterfaceAccess().getSignaturesAssignment_4_2(), "rule__Interface__SignaturesAssignment_4_2");
					put(grammarAccess.getInterfaceAccess().getSignaturesAssignment_4_3_1(), "rule__Interface__SignaturesAssignment_4_3_1");
					put(grammarAccess.getComponentAccess().getNameAssignment_2(), "rule__Component__NameAssignment_2");
					put(grammarAccess.getComponentAccess().getProvidedRolesAssignment_4_2(), "rule__Component__ProvidedRolesAssignment_4_2");
					put(grammarAccess.getComponentAccess().getProvidedRolesAssignment_4_3_1(), "rule__Component__ProvidedRolesAssignment_4_3_1");
					put(grammarAccess.getComponentAccess().getRequiredRolesAssignment_5_2(), "rule__Component__RequiredRolesAssignment_5_2");
					put(grammarAccess.getComponentAccess().getRequiredRolesAssignment_5_3_1(), "rule__Component__RequiredRolesAssignment_5_3_1");
					put(grammarAccess.getComponentAccess().getBehaviorDescriptionAssignment_6_1(), "rule__Component__BehaviorDescriptionAssignment_6_1");
					put(grammarAccess.getSignatureAccess().getNameAssignment_2(), "rule__Signature__NameAssignment_2");
					put(grammarAccess.getSignatureAccess().getReturnTypeAssignment_4_1(), "rule__Signature__ReturnTypeAssignment_4_1");
					put(grammarAccess.getSignatureAccess().getParametersAssignment_5_2(), "rule__Signature__ParametersAssignment_5_2");
					put(grammarAccess.getSignatureAccess().getParametersAssignment_5_3_1(), "rule__Signature__ParametersAssignment_5_3_1");
					put(grammarAccess.getParameterAccess().getNameAssignment_1(), "rule__Parameter__NameAssignment_1");
					put(grammarAccess.getParameterAccess().getTypeAssignment_4(), "rule__Parameter__TypeAssignment_4");
					put(grammarAccess.getProvidedRoleAccess().getNameAssignment_1(), "rule__ProvidedRole__NameAssignment_1");
					put(grammarAccess.getProvidedRoleAccess().getProvidedInterfaceAssignment_4(), "rule__ProvidedRole__ProvidedInterfaceAssignment_4");
					put(grammarAccess.getRequiredRoleAccess().getNameAssignment_1(), "rule__RequiredRole__NameAssignment_1");
					put(grammarAccess.getRequiredRoleAccess().getRequiredInterfaceAssignment_4(), "rule__RequiredRole__RequiredInterfaceAssignment_4");
					put(grammarAccess.getBehaviorDescriptionAccess().getActionsAssignment_3_2(), "rule__BehaviorDescription__ActionsAssignment_3_2");
					put(grammarAccess.getBehaviorDescriptionAccess().getActionsAssignment_3_3_1(), "rule__BehaviorDescription__ActionsAssignment_3_3_1");
					put(grammarAccess.getAction_ImplAccess().getNameAssignment_2(), "rule__Action_Impl__NameAssignment_2");
					put(grammarAccess.getAction_ImplAccess().getPredecessorAssignment_4_1(), "rule__Action_Impl__PredecessorAssignment_4_1");
					put(grammarAccess.getAction_ImplAccess().getSuccessorAssignment_5_1(), "rule__Action_Impl__SuccessorAssignment_5_1");
					put(grammarAccess.getInternalActionAccess().getNameAssignment_2(), "rule__InternalAction__NameAssignment_2");
					put(grammarAccess.getInternalActionAccess().getPredecessorAssignment_4_1(), "rule__InternalAction__PredecessorAssignment_4_1");
					put(grammarAccess.getInternalActionAccess().getSuccessorAssignment_5_1(), "rule__InternalAction__SuccessorAssignment_5_1");
					put(grammarAccess.getExternalCallAccess().getNameAssignment_1(), "rule__ExternalCall__NameAssignment_1");
					put(grammarAccess.getExternalCallAccess().getPredecessorAssignment_3_1(), "rule__ExternalCall__PredecessorAssignment_3_1");
					put(grammarAccess.getExternalCallAccess().getSuccessorAssignment_4_1(), "rule__ExternalCall__SuccessorAssignment_4_1");
					put(grammarAccess.getExternalCallAccess().getRequiredServiceAssignment_6(), "rule__ExternalCall__RequiredServiceAssignment_6");
					put(grammarAccess.getExternalCallAccess().getRequiredRoleOfServiceAssignment_8(), "rule__ExternalCall__RequiredRoleOfServiceAssignment_8");
					put(grammarAccess.getLoopAccess().getNameAssignment_2(), "rule__Loop__NameAssignment_2");
					put(grammarAccess.getLoopAccess().getPredecessorAssignment_4_1(), "rule__Loop__PredecessorAssignment_4_1");
					put(grammarAccess.getLoopAccess().getSuccessorAssignment_5_1(), "rule__Loop__SuccessorAssignment_5_1");
					put(grammarAccess.getLoopAccess().getLoopActionsAssignment_6_2(), "rule__Loop__LoopActionsAssignment_6_2");
					put(grammarAccess.getLoopAccess().getLoopActionsAssignment_6_3_1(), "rule__Loop__LoopActionsAssignment_6_3_1");
					put(grammarAccess.getBranchAccess().getNameAssignment_2(), "rule__Branch__NameAssignment_2");
					put(grammarAccess.getBranchAccess().getPredecessorAssignment_4_1(), "rule__Branch__PredecessorAssignment_4_1");
					put(grammarAccess.getBranchAccess().getSuccessorAssignment_5_1(), "rule__Branch__SuccessorAssignment_5_1");
					put(grammarAccess.getBranchAccess().getBranchPathsAssignment_6_2(), "rule__Branch__BranchPathsAssignment_6_2");
					put(grammarAccess.getBranchAccess().getBranchPathsAssignment_6_3_1(), "rule__Branch__BranchPathsAssignment_6_3_1");
					put(grammarAccess.getBranchPathAccess().getNameAssignment_2(), "rule__BranchPath__NameAssignment_2");
					put(grammarAccess.getBranchPathAccess().getPathActionsAssignment_4_2(), "rule__BranchPath__PathActionsAssignment_4_2");
					put(grammarAccess.getBranchPathAccess().getPathActionsAssignment_4_3_1(), "rule__BranchPath__PathActionsAssignment_4_3_1");
					put(grammarAccess.getComplexTypeAccess().getNameAssignment_2(), "rule__ComplexType__NameAssignment_2");
					put(grammarAccess.getSimpleTypeAccess().getTypeInstanceAssignment_3(), "rule__SimpleType__TypeInstanceAssignment_3");
					put(grammarAccess.getAssemblyContextAccess().getNameAssignment_1(), "rule__AssemblyContext__NameAssignment_1");
					put(grammarAccess.getAssemblyContextAccess().getInstantiatedComponentAssignment_4(), "rule__AssemblyContext__InstantiatedComponentAssignment_4");
					put(grammarAccess.getProvidedDelegationConnectorAccess().getNameAssignment_1(), "rule__ProvidedDelegationConnector__NameAssignment_1");
					put(grammarAccess.getProvidedDelegationConnectorAccess().getInnerAssemblyContextAssignment_4(), "rule__ProvidedDelegationConnector__InnerAssemblyContextAssignment_4");
					put(grammarAccess.getProvidedDelegationConnectorAccess().getOuterAssemblyContextAssignment_6(), "rule__ProvidedDelegationConnector__OuterAssemblyContextAssignment_6");
					put(grammarAccess.getProvidedDelegationConnectorAccess().getInnerProvidedRoleAssignment_8(), "rule__ProvidedDelegationConnector__InnerProvidedRoleAssignment_8");
					put(grammarAccess.getProvidedDelegationConnectorAccess().getOuterProvidedRoleAssignment_10(), "rule__ProvidedDelegationConnector__OuterProvidedRoleAssignment_10");
					put(grammarAccess.getRequiredDelegationConnectorAccess().getNameAssignment_1(), "rule__RequiredDelegationConnector__NameAssignment_1");
					put(grammarAccess.getRequiredDelegationConnectorAccess().getInnerAssemblyContextAssignment_4(), "rule__RequiredDelegationConnector__InnerAssemblyContextAssignment_4");
					put(grammarAccess.getRequiredDelegationConnectorAccess().getOuterAssemblyContextAssignment_6(), "rule__RequiredDelegationConnector__OuterAssemblyContextAssignment_6");
					put(grammarAccess.getRequiredDelegationConnectorAccess().getInnerRequiredRoleAssignment_8(), "rule__RequiredDelegationConnector__InnerRequiredRoleAssignment_8");
					put(grammarAccess.getRequiredDelegationConnectorAccess().getOuterRequiredRoleAssignment_10(), "rule__RequiredDelegationConnector__OuterRequiredRoleAssignment_10");
					put(grammarAccess.getAssemblyConnectorAccess().getNameAssignment_1(), "rule__AssemblyConnector__NameAssignment_1");
					put(grammarAccess.getAssemblyConnectorAccess().getConnectedProvidedRoleAssignment_4(), "rule__AssemblyConnector__ConnectedProvidedRoleAssignment_4");
					put(grammarAccess.getAssemblyConnectorAccess().getConnectedRequiredRoleAssignment_6(), "rule__AssemblyConnector__ConnectedRequiredRoleAssignment_6");
					put(grammarAccess.getAssemblyConnectorAccess().getConnectedProvidedAssemblyContextAssignment_8(), "rule__AssemblyConnector__ConnectedProvidedAssemblyContextAssignment_8");
					put(grammarAccess.getAssemblyConnectorAccess().getConnectedRequiredAssemblyContextAssignment_10(), "rule__AssemblyConnector__ConnectedRequiredAssemblyContextAssignment_10");
					put(grammarAccess.getContainerAccess().getNameAssignment_2(), "rule__Container__NameAssignment_2");
					put(grammarAccess.getLinkAccess().getNameAssignment_1(), "rule__Link__NameAssignment_1");
					put(grammarAccess.getLinkAccess().getLinkedContainersAssignment_5(), "rule__Link__LinkedContainersAssignment_5");
					put(grammarAccess.getLinkAccess().getLinkedContainersAssignment_6_1(), "rule__Link__LinkedContainersAssignment_6_1");
					put(grammarAccess.getAllocationContextAccess().getNameAssignment_1(), "rule__AllocationContext__NameAssignment_1");
					put(grammarAccess.getAllocationContextAccess().getAllocatedContainerAssignment_4(), "rule__AllocationContext__AllocatedContainerAssignment_4");
					put(grammarAccess.getAllocationContextAccess().getAllocatedAssemblyContextAssignment_6(), "rule__AllocationContext__AllocatedAssemblyContextAssignment_6");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalCbsmDslParser typedParser = (InternalCbsmDslParser) parser;
			typedParser.entryRuleViewType();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public CbsmDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CbsmDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
