<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="componentBasedSystemModel" nsURI="http://sdq.ipd.kit.edu/componentBasedSystemModel"
    nsPrefix="componentBasedSystemModel">
  <eSubpackages name="core" nsURI="http://sdq.ipd.kit.edu/componentBasedSystemModel/core"
      nsPrefix="core">
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="repository" nsURI="http://sdq.ipd.kit.edu/componentBasedSystemModel/repository"
      nsPrefix="repository">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Repository">
      <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
          eType="#//repository/Interface" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
          eType="#//repository/Component" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypes" upperBound="-1"
          eType="#//repository/DataType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//core/NamedElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="NoSignaturesEquivalent"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="NoSignaturesEquivalent" value="self.signatures->forAll(signature1|&#xA;&#x9;&#x9;&#x9;&#x9;not(self.signatures->exists(signature2|&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;signature1 &lt;> signature2 and &#xA;&#x9;&#x9;&#x9;&#x9;&#x9;signature1.name = signature2.name and&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;signature1.parameters->size() = signature2.parameters->size() and&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;signature1.parameters->forAll(parameter1|&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;signature2.parameters->at(signature1.parameters->indexOf(parameter1)).type = parameter1.type)&#xA;&#x9;&#x9;&#x9;&#x9;))&#xA;&#x9;&#x9;&#x9;)"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="signatures" upperBound="-1"
          eType="#//repository/Signature" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedRoles" upperBound="-1"
          eType="#//repository/ProvidedRole" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredRoles" upperBound="-1"
          eType="#//repository/RequiredRole" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="behaviorDescription"
          eType="#//repository/behavior/BehaviorDescription" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Role" abstract="true" eSuperTypes="#//core/NamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidedRole" eSuperTypes="#//repository/Role">
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterface" lowerBound="1"
          eType="#//repository/Interface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RequiredRole" eSuperTypes="#//repository/Role">
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterface" lowerBound="1"
          eType="#//repository/Interface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeComponent" eSuperTypes="#//repository/Component #//assembly/CompositeElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Signature" eSuperTypes="#//core/NamedElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="NoParameterWithSameName"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="NoParameterWithSameName" value="self.parameters->forAll(parameter1|&#xA;&#x9;&#x9;&#x9;&#x9;not(self.parameters->exists(parameter2|&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;parameter1 &lt;> parameter2 and &#xA;&#x9;&#x9;&#x9;&#x9;&#x9;parameter1.name = parameter2.name&#xA;&#x9;&#x9;&#x9;&#x9;))&#xA;&#x9;&#x9;&#x9;)"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" lowerBound="1"
          eType="#//repository/DataType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//repository/Parameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//repository/DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComplexType" eSuperTypes="#//core/NamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeInstance" lowerBound="1"
          eType="#//repository/SimpleTypeInstance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SimpleTypeInstance">
      <eLiterals name="Boolean"/>
      <eLiterals name="Char" value="1"/>
      <eLiterals name="Date" value="2"/>
      <eLiterals name="Double" value="3"/>
      <eLiterals name="Float" value="4"/>
      <eLiterals name="List" value="5"/>
      <eLiterals name="Int" value="6"/>
      <eLiterals name="Long" value="7"/>
      <eLiterals name="Map" value="8"/>
      <eLiterals name="String" value="9"/>
    </eClassifiers>
    <eSubpackages name="behavior" nsURI="http://sdq.ipd.kit.edu/componentBasedSystemModel/repository/behavior"
        nsPrefix="behavior">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
        <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
        <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="BehaviorDescription">
        <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
            eType="#//repository/behavior/Action" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//core/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="predecessor" eType="#//repository/behavior/Action"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="successor" eType="#//repository/behavior/Action"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InternalAction" eSuperTypes="#//repository/behavior/Action"/>
      <eClassifiers xsi:type="ecore:EClass" name="ExternalCall" eSuperTypes="#//repository/behavior/Action">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
          <details key="constraints" value="RequiredRolesInterfaceContainsSignature"/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="RequiredRolesInterfaceContainsSignature" value="&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;self.requiredRoleOfService.requiredInterface.signatures->exists(signature|&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;signature = self.requiredService&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;)"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="requiredService" lowerBound="1"
            eType="#//repository/Signature"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="requiredRoleOfService"
            lowerBound="1" eType="#//repository/RequiredRole"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//repository/behavior/Action">
        <eStructuralFeatures xsi:type="ecore:EReference" name="loopActions" upperBound="-1"
            eType="#//repository/behavior/Action" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Branch" eSuperTypes="#//repository/behavior/Action">
        <eStructuralFeatures xsi:type="ecore:EReference" name="branchPaths" upperBound="-1"
            eType="#//repository/behavior/BranchPath" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BranchPath" eSuperTypes="#//core/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="pathActions" upperBound="-1"
            eType="#//repository/behavior/Action" containment="true"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="assembly" nsURI="http://sdq.ipd.kit.edu/componentBasedSystemModel/assembly"
      nsPrefix="assembly">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="AssemblyContext" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instantiatedComponent"
          lowerBound="1" eType="#//repository/Component"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyContextProvidedRoles"
          upperBound="-1" eType="#//repository/ProvidedRole" volatile="true" transient="true"
          derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="derivation" value="self.instantiatedComponent.providedRoles"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyContextRequiredRoles"
          upperBound="-1" eType="#//repository/RequiredRole" volatile="true" transient="true"
          derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="derivation" value="self.instantiatedComponent.requiredRoles"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentCompositeElement"
          lowerBound="1" eType="#//assembly/CompositeElement" eOpposite="#//assembly/CompositeElement/containedAssemblyContexts"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeElement" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="CompositeElementDoesNotContainItself"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="CompositeElementDoesNotContainItself" value="self.containedAssemblyContexts->forAll(assemblyContext|&#xA;&#x9;&#x9;&#x9;&#x9;assemblyContext.instantiatedComponent &lt;> self&#xA;&#x9;&#x9;&#x9;)"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containedAssemblyContexts"
          upperBound="-1" eType="#//assembly/AssemblyContext" containment="true" eOpposite="#//assembly/AssemblyContext/parentCompositeElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//assembly/CompositeElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="systemProvidedRoles"
          lowerBound="1" upperBound="-1" eType="#//repository/ProvidedRole"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="systemRequiredRoles"
          upperBound="-1" eType="#//repository/RequiredRole"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="systemConnectors" upperBound="-1"
          eType="#//assembly/Connector" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Connector" abstract="true" eSuperTypes="#//core/NamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="DelegationConnector" abstract="true"
        eSuperTypes="#//assembly/Connector">
      <eTypeParameters name="T">
        <eBounds eClassifier="#//repository/Role"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="innerRole" lowerBound="1">
        <eGenericType eTypeParameter="#//assembly/DelegationConnector/T"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="innerAssemblyContext"
          lowerBound="1" eType="#//assembly/AssemblyContext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outerRole" lowerBound="1">
        <eGenericType eTypeParameter="#//assembly/DelegationConnector/T"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outerAssemblyContext"
          lowerBound="1" eType="#//assembly/AssemblyContext"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidedDelegationConnector">
      <eGenericSuperTypes eClassifier="#//assembly/DelegationConnector">
        <eTypeArguments eClassifier="#//repository/ProvidedRole"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RequiredDelegationConnector">
      <eGenericSuperTypes eClassifier="#//assembly/DelegationConnector">
        <eTypeArguments eClassifier="#//repository/RequiredRole"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssemblyConnector" eSuperTypes="#//assembly/Connector">
      <eStructuralFeatures xsi:type="ecore:EReference" name="connectedProvidedRole"
          lowerBound="1" eType="#//repository/ProvidedRole"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connectedRequiredRole"
          lowerBound="1" eType="#//repository/RequiredRole"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="environment" nsURI="http://sdq.ipd.kit.edu/componentBasedSystemModel/environment"
      nsPrefix="environment">
    <eClassifiers xsi:type="ecore:EClass" name="Environment">
      <eStructuralFeatures xsi:type="ecore:EReference" name="containers" upperBound="-1"
          eType="#//environment/Container" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
          eType="#//environment/Link" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Container" eSuperTypes="#//core/NamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkedContainers" lowerBound="2"
          upperBound="-1" eType="#//environment/Container"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="allocation" nsURI="http://sdq.ipd.kit.edu/componentBasedSystemModel/allocation"
      nsPrefix="allocation">
    <eClassifiers xsi:type="ecore:EClass" name="Allocation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocationContexts" upperBound="-1"
          eType="#//allocation/AllocationContext" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AllocationContext" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedContainer" lowerBound="1"
          eType="#//environment/Container"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedAssemblyContext"
          lowerBound="1" eType="#//assembly/AssemblyContext"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
