/**
 * generated by Xtext 2.9.2
 */
package edu.kit.ipd.sdq.cbsmdsl.ui.contentassist;

import edu.kit.ipd.sdq.cbsmdsl.ui.contentassist.AbstractCbsmDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CbsmDslProposalProvider extends AbstractCbsmDslProposalProvider {
}
