/*
 * generated by Xtext
 */
package edu.kit.ipd.sdq.cbsmdsl.ui.tests;

import com.google.inject.Injector;
import edu.kit.ipd.sdq.cbsmdsl.ui.internal.CbsmdslActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class CbsmDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CbsmdslActivator.getInstance().getInjector("edu.kit.ipd.sdq.cbsmdsl.CbsmDsl");
	}

}
