/**
 * generated by Xtext 2.9.2
 */
package edu.kit.ipd.sdq.cbsmdsl.ui;

import edu.kit.ipd.sdq.cbsmdsl.ui.AbstractCbsmDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CbsmDslUiModule extends AbstractCbsmDslUiModule {
  public CbsmDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
