/*
<<<<<<< HEAD
 * generated by Xtext 2.9.1
=======
 * generated by Xtext
>>>>>>> 624daea66344a9d43745cf9a36e8187215bc46ca
 */
package edu.kit.ipd.sdq.cbsmdsl.ui;

import com.google.inject.Injector;
import edu.kit.ipd.sdq.cbsmdsl.ui.internal.CbsmdslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CbsmDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CbsmdslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CbsmdslActivator.getInstance().getInjector(CbsmdslActivator.EDU_KIT_IPD_SDQ_CBSMDSL_CBSMDSL);
	}
	
}
