/*
 * generated by Xtext 2.9.2
 */
package edu.kit.ipd.sdq.cbsmdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CbsmDslStandaloneSetup extends CbsmDslStandaloneSetupGenerated {

	def static void doSetup() {
		new CbsmDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
