/*
 * generated by Xtext 2.9.2
 */
package edu.kit.ipd.sdq.cbsmdsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CbsmDslRuntimeModule extends AbstractCbsmDslRuntimeModule {
}
